name: Build APK

# Triggers the workflow on push or pull request events but only for the main branch
# Build is triggered with successful push of a new Tag (No need to initiate the build manually via github)
on:
  push:
    tags:
      - v*

jobs:
  apk_build:
    runs-on: ubuntu-latest
    steps:
      # Setup the flutter environment.
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: ' 3.7.7'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Build apk.
      - run: flutter build apk

      # Release generated APK.
      - uses: ncipollo/release-action@v1
        with:
          name: release-apk
          artifacts: build/app/outputs/apk/release/*.apk
          token: ${{ secrets.ACTIONS_TOKEN }}
