name: Generate Documentation

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.10'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Generate documentation
        run: dart doc .

      - name: Archive documentation
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: pleier_docs
          path: doc/api

      - name: Check out pull request branch
        uses: actions/checkout@v4 # Updated to v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Download documentation
        uses: actions/download-artifact@v4 # Updated to v4
        id: download
        with:
          name: pleier_docs
          path: doc/api

      - name: Display structure of downloaded files
        run: ls -R

      - name: Commit and push documentation
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -f doc/api
          git commit -m "Add generated documentation"
          git push
